### PR TITLE
Kodi Icon Addition, Icon If/Else Cleanup, Local Icon Files, and Added Playing Text

### PR DESCRIPTION
**Pull request by JPKribs**
Added in logic to skip most of the Browser If/Else in exchange for a single check for Jellyfin Web followed by either checking for Browser Type if true or checking for other apps if false. Not totally necessary but just made more sense to me not to check for Jellyfin Web more than once.

Added in logic to get the Kodi icon if using JellyCon or Kodi for Jellyfin. 

Moved all icons in use to the project itself to prevent unnecessary calls to Jellyfin. Also eliminates the issue that some SVGs dont exist on some versions of Jellyfin Web. Also enables usage of Infuse (Apple TV) icon. Couldn't personally get an SVG to work for Infuse so I'm still just using the PNG from their site.

Adjusted Icon colors to try and better match the SVG to the client colors.

Removed the Server URL in the comments of the Dashboard.

Added a tag in the playback container for "Playing" with the NowPlayingItem.Name in there.

Sorry for the double submission on icon changes!

### CODE REVIEW

**Comment by fallenbagel** [comment]
What are those binary files?

**Comment by JPKribs** [comment]
Looks like those are visual studios related. Let me clear these out and I can resubmit. I'm not sure why those got lumped in with the pull from VS.

**Comment by fallenbagel** [comment]
> Looks like those are visual studios related. Let me clear these out and I can resubmit. I'm not sure why those got lumped in with the pull from VS.

Probably because it wasn't added to .git ignore 🤔

**Comment by JPKribs** [comment]
Resubmitting with files pulled.

**Pull request closed without merging**
